Repository refined-bitbucket/refined-bitbucket, pull requests merged in 2018-02, with the labels that each got.

#137 Update prism
  CHANGELOG.md
  README.md
  src/syntax-highlight/language-ext.js
  src/syntax-highlight/source-handler.js
  src/syntax-highlight/source-handler.spec.js
  src/vendor/prism.js
Labels: feature

#146 fix: syntax highlighting not working in v3.4 - v3.5
  CHANGELOG.md
  src/background.js
  src/main.js
Labels: bug

#153 Bring old link color (blue) back to titles
  CHANGELOG.md
  README.md
  src/background.js
  src/main.js
  src/old-link-color.css
  src/options.html
Labels: feature

#156 feat: Don't include diff's pluses and minuses in clipboard
  CHANGELOG.md
  README.md
  src/background.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.css
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.spec.js
  src/diff-pluses-and-minuses/index.js
  src/main.js
  src/options.html
  src/syntax-highlight/syntax-highlight.spec.js
  test/setup-jsdom.js
Labels: feature

#157 fix(close-anchor-branch): should only apply when creating PRs
  CHANGELOG.md
  src/main.js
Labels: bug

#158 fix: word diffs no longer remove syntax highlight
  CHANGELOG.md
  README.md
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.spec.js
  src/main.js
  src/observe-for-word-diffs.js
  src/syntax-highlight/source-handler.js
  src/syntax-highlight/source-handler.spec.js
  src/syntax-highlight/syntax-highlight.js
  src/syntax-highlight/syntax-highlight.spec.js
  src/vendor/prism.js
Labels: bug, enhancement

#159 ft: code review features in branch compare
  CHANGELOG.md
  src/diff-ignore/diff-ignore.js
  src/diff-ignore/diff-ignore.spec.js
  src/diff-ignore/index.js
  src/load-all-diffs/load-all-diffs.js
  src/main.js
  src/occurrences-highlighter/index.js
  src/occurrences-highlighter/occurrences-highlighter.js
  src/page-detect.js
  src/wait-for-pullrequest.js
Labels: enhancement

#162 fix: don't remove unintended characters from line diffs
  CHANGELOG.md
  src/augment-pr-entry/augment-pr-entry.spec.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.spec.js
  src/syntax-highlight/syntax-highlight.js
Labels: bug

#165 fix: don't remove unintended chars from diff (p2)
  CHANGELOG.md
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.spec.js
Labels: bug
