Repository refined-bitbucket/refined-bitbucket, pull requests merged in 2018-05, with the labels that each got.

#209 Custom Tab Indentation
  README.md
  src/background.js
  src/main.js
  src/options.html
  src/tab-size/index.js
  src/tab-size/tab-size.js
Labels: feature

#217 fix(syntax-highlight): Word diffs no longer removed
  CHANGELOG.md
  package.json
  src/vendor/prism.js
Labels: bug

#215 feat: Add "Copy filename" button
  CHANGELOG.md
  README.md
  src/background.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.js
  src/insert-copy-filename/index.js
  src/insert-copy-filename/insert-copy-filename.js
  src/insert-copy-filename/insert-copy-filename.spec.js
  src/main.js
  src/options.html
Labels: feature, ready-for-review
