Repository refined-bitbucket/refined-bitbucket, pull requests merged in 2018-03, with the labels that each got.

#176 fix(options): allow disable update notifications
  CHANGELOG.md
  src/background.js
  src/options.html
Labels: enhancement

#180 fix: default options saved as arrays
  src/background.js
Labels: bug

#179 fix: "Add source branch" feature
  CHANGELOG.md
  src/main.js
Labels: bug

#166 Added logo & icons
  CONTRIBUTORS.md
  README.md
  logo-full-white.svg
  logo-full.svg
  src/icon.svg
  src/icon128.png
  src/icon48.png
  src/icon_128px.png
  src/icon_16px.png
  src/icon_256px.png
  src/icon_32px.png
  src/icon_48px.png
  src/icon_64px.png
  src/manifest.json
Labels: enhancement

#164 [WIP] ft: badge with number of commits in pull request
  CHANGELOG.md
  README.md
  src/augment-pr-entry/augment-pr-entry.js
  src/background.js
  src/main.js
  src/options.html
  src/pullrequest-commit-amount/index.js
  src/pullrequest-commit-amount/pullrequest-commit-amount.css
  src/pullrequest-commit-amount/pullrequest-commit-amount.js
  src/pullrequest-commit-amount/pullrequest-commit-amount.spec.js
  src/syntax-highlight/syntax-highlight.js
Labels: feature

#174 add syntax highlight support for Jenkinsfile & Vagrantfile
  CHANGELOG.md
  src/syntax-highlight/language-ext.js
  src/syntax-highlight/source-handler.js
  src/syntax-highlight/source-handler.spec.js
  src/syntax-highlight/syntax-highlight.js
Labels: enhancement

#187 Display author of the latest activity on a pull request
  CHANGELOG.md
  src/augment-pr-entry/augment-pr-entry.js
  src/augment-pr-entry/augment-pr-entry.spec.js
Labels: feature

#177 fix(diff): extra leading pluses/minuses in diff
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.js
  src/diff-pluses-and-minuses/diff-pluses-and-minuses.spec.js
  src/observe-for-word-diffs.js
Labels: bug
