Repository refined-bitbucket/refined-bitbucket, pull requests merged in 2020-11, with the labels that each got.

#342 Collapse pull request side menus on load
  src/background.js
  src/collapse-pull-request-side-menus/collapse-pull-request-side-menus.js
  src/collapse-pull-request-side-menus/index.js
  src/main.js
  src/options.html
  src/sticky-header/sticky-header.js
Labels: feature, new-ui, ready-for-review

#350 PR/Branches badges side menu: Re-insert if any side menu mount/re-mount
  src/background-for-requests.js
  src/sidebar-counters/sidebar-counters.css
  src/sidebar-counters/sidebar-counters.js
  src/sidebar-counters/sidebar-counters.spec.js
Labels: enhancement, ready-for-review

#362 Fix Augment PR entry
  src/augment-pr-entry/augment-pr-entry.js
  src/augment-pr-entry/augment-pr-entry.spec.js
  src/show-comments/show-comments.spec.js
Labels: ready-for-review

#388 Adds 'Compact' FileTree mode for 'new' Pull Request UI
  CONTRIBUTORS.md
  README.md
  src/background.js
  src/compact-pull-request-file-tree/compact-pull-request-file-tree.js
  src/compact-pull-request-file-tree/index.js
  src/main.js
  src/options.html
Labels: ready-for-review
